import { Component, computed, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatDialog } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { MatTooltipModule } from '@angular/material/tooltip';
import { firstValueFrom } from 'rxjs';
import { TranslationService } from '../../../../shared/infrastructure/i18n/translation.service';
import { Callout } from '../../../../shared/presentation/components/callout/callout';
import { ToastService } from '../../../../shared/presentation/components/toast-host/toast.service';
import { LocalizedDatePipe } from '../../../../shared/presentation/pipes/localized-date.pipe';
import { TranslatePipe } from '../../../../shared/presentation/pipes/translate.pipe';
import { TenantNotificationsStore } from '../../../application/tenant-notifications.store';
import { NotificationStatus } from '../../../domain/model/notification-status.enum';
import { NotificationType } from '../../../domain/model/notification-type.enum';
import { CommunicationTabs } from '../../components/communication-tabs/communication-tabs';
import { PublishAnnouncementDialog } from '../../components/publish-announcement-dialog/publish-announcement-dialog';
import { CommunicationStatusBadge } from '../../components/status-badge/status-badge';

/**
 * Tenant notifications: the announcements and incident notices published by the administrator
 * (US-34, US-35) and the ones generated by the platform, with their delivery and read status.
 */
@Component({
  selector: 'app-tenant-notifications',
  imports: [
    Callout,
    CommunicationStatusBadge,
    CommunicationTabs,
    LocalizedDatePipe,
    MatButtonModule,
    MatCardModule,
    MatFormFieldModule,
    MatIconModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatTooltipModule,
    TranslatePipe,
  ],
  templateUrl: './tenant-notifications.html',
  styleUrl: '../../styles/communication.css',
})
export class TenantNotifications {
  protected readonly store = inject(TenantNotificationsStore);
  private readonly dialog = inject(MatDialog);
  private readonly toast = inject(ToastService);
  private readonly i18n = inject(TranslationService);

  protected readonly types = Object.values(NotificationType);
  protected readonly statuses = Object.values(NotificationStatus);
  protected readonly type = signal<NotificationType | 'ALL'>('ALL');
  protected readonly status = signal<NotificationStatus | 'ALL'>('ALL');
  protected readonly pageIndex = signal(0);
  protected readonly pageSize = 10;

  protected readonly filtered = computed(() =>
    this.store
      .notifications()
      .filter((n) => this.type() === 'ALL' || n.type === this.type())
      .filter((n) => this.status() === 'ALL' || n.status === this.status()),
  );
  protected readonly page = computed(() =>
    this.filtered().slice(this.pageIndex() * this.pageSize, (this.pageIndex() + 1) * this.pageSize),
  );

  constructor() {
    void this.store.load();
  }

  protected setType(value: NotificationType | 'ALL'): void {
    this.type.set(value);
    this.pageIndex.set(0);
  }

  protected setStatus(value: NotificationStatus | 'ALL'): void {
    this.status.set(value);
    this.pageIndex.set(0);
  }

  protected changePage(event: PageEvent): void {
    this.pageIndex.set(event.pageIndex);
  }

  protected async publish(): Promise<void> {
    this.store.lastPublication.set(null);
    const ref = this.dialog.open<PublishAnnouncementDialog, void, boolean>(
      PublishAnnouncementDialog,
      { width: '620px' },
    );
    if (await firstValueFrom(ref.afterClosed())) {
      this.pageIndex.set(0);
      const result = this.store.lastPublication();
      this.toast.show(
        'success',
        this.i18n.t('communication.publish.sent', { count: result?.sent ?? 0 }),
      );
    }
  }

  protected async retry(notificationId: string): Promise<void> {
    if (await this.store.retry(notificationId)) {
      this.toast.show('success', this.i18n.t('communication.notifications.retried'));
    } else if (this.store.error()) {
      this.toast.show('error', this.i18n.t(`communication.errors.${this.store.error()}`));
      this.store.clearError();
    }
  }

  protected unitsWithoutTenant(): string {
    return (this.store.lastPublication()?.unitsWithoutTenant ?? [])
      .map((unit) => unit.code)
      .join(', ');
  }
}
