import { BaseEntity } from '../../../shared/domain/model/base-entity';
import { CommunicationError, CommunicationErrorCode } from './communication-error';
import { NotificationChannel } from './notification-channel.enum';
import { NotificationStatus } from './notification-status.enum';
import { NotificationType } from './notification-type.enum';
import { NotifyTenantCommand } from './notify-tenant.command';

interface TenantNotificationProps {
  id: string;
  tenantId: string;
  commercialUnitId: string | null;
  galleryAdministratorId: string;
  type: NotificationType;
  title: string;
  body: string;
  channel: NotificationChannel;
  status: NotificationStatus;
  /** Whether the tenant already opened it (GetUnreadNotificationsCountQuery). */
  read: boolean;
  createdAt: Date;
  /** Resource that originated it, such as a conversation or a bill. */
  referenceId: string | null;
}

/**
 * Notification sent to a tenant (Aggregate Root), either published by the administrator or
 * generated by an event such as `UtilityBillIssued`. It starts as pending and ends sent or failed.
 */
export class TenantNotification implements BaseEntity {
  static readonly titleMaxLength = 120;
  static readonly bodyMaxLength = 1000;

  private readonly props: TenantNotificationProps;

  constructor(notification: TenantNotificationProps) {
    this.props = { ...notification };
  }

  /** NotifyTenantCommand: the notification is created pending and gets its id when saved. */
  static create(command: NotifyTenantCommand, now: Date = new Date()): TenantNotification {
    if (!TenantNotification.isValidTitle(command.title)) {
      throw new CommunicationError(CommunicationErrorCode.InvalidNotificationTitle);
    }
    if (!TenantNotification.isValidBody(command.body)) {
      throw new CommunicationError(CommunicationErrorCode.InvalidNotificationBody);
    }
    return new TenantNotification({
      id: '',
      tenantId: command.tenantId,
      commercialUnitId: command.commercialUnitId,
      galleryAdministratorId: command.galleryAdministratorId,
      type: command.type,
      title: command.title.trim(),
      body: command.body.trim(),
      channel: command.channel,
      status: NotificationStatus.Pending,
      read: false,
      createdAt: now,
      referenceId: command.referenceId,
    });
  }

  get id(): string {
    return this.props.id;
  }

  get tenantId(): string {
    return this.props.tenantId;
  }

  get commercialUnitId(): string | null {
    return this.props.commercialUnitId;
  }

  get galleryAdministratorId(): string {
    return this.props.galleryAdministratorId;
  }

  get type(): NotificationType {
    return this.props.type;
  }

  get title(): string {
    return this.props.title;
  }

  get body(): string {
    return this.props.body;
  }

  get channel(): NotificationChannel {
    return this.props.channel;
  }

  get status(): NotificationStatus {
    return this.props.status;
  }

  get read(): boolean {
    return this.props.read;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get referenceId(): string | null {
    return this.props.referenceId;
  }

  get isFailed(): boolean {
    return this.props.status === NotificationStatus.Failed;
  }

  /** Delivery confirmed (TenantNotifiedEvent). */
  markSent(): TenantNotification {
    return new TenantNotification({ ...this.props, status: NotificationStatus.Sent });
  }

  markFailed(): TenantNotification {
    return new TenantNotification({ ...this.props, status: NotificationStatus.Failed });
  }

  /** A failed notification goes back to pending to be delivered again. */
  retry(): TenantNotification {
    if (!this.isFailed) throw new CommunicationError(CommunicationErrorCode.NotificationNotFailed);
    return new TenantNotification({ ...this.props, status: NotificationStatus.Pending });
  }

  static isValidTitle(title: string): boolean {
    const trimmed = title.trim();
    return trimmed.length > 0 && trimmed.length <= TenantNotification.titleMaxLength;
  }

  static isValidBody(body: string): boolean {
    const trimmed = body.trim();
    return trimmed.length > 0 && trimmed.length <= TenantNotification.bodyMaxLength;
  }
}
